### ISSUE TITLE
Support for PicKit 5 programmer / debugger

### ISSUE THREAD

**Issue by memen45** [callwyat/mplab-extension#10]
PicKit 5 was released in the beginning of this year. I do not see it listed under Supported Tools. I believe the PicKit 5 is quite similar to the PicKit 4. Is it possible to add support for this tool?

`<platformTool>PK5Tool</platformTool>`

**Comment by callwyat** [comment]
Support for the PICKIT5 should work in version 0.1.12, which was just released. If the issue persists, please reopen this issue.
