### ISSUE TITLE
Support for parallel make command

### ISSUE THREAD

**Issue by memen45** [callwyat/mplab-extension#11]
MPLAB X enables parallel make command by default, using the `make -j4` or `make -j16` command. Depending on the number of cores you have available. Typically, 2n is used. Is it possible to either enable this by default or add an option to the tasks.json file?

**Comment by callwyat** [comment]
Does adding these arguments into this field not work?

<img width="901" alt="Screenshot 2023-10-04 at 9 11 29 PM" src="https://github.com/callwyat/mplab-extension/assets/43596583/6e3f98be-106a-4480-9a5c-debfbc30642b">

**Comment by xgonc** [comment]
It doesn't. `-jx` is a make related argument, not compiler related.

**Comment by callwyat** [comment]
I have published a pre-release version of the extension, v0.1.23, that replaces the existing `configuration` and `debug` properties in favor of a `args` property that will allow you to put any arguments you want directly after the "make" command. Please test it out and let me know if it works for you. If it works for you, I'll publish a normal release right away. If I don't hear anything back by Friday, I'll assume it's fine and publish the normal release. If it doesn't solve this issue, please let me know!

**Comment by callwyat** [comment]
v0.1.24 has been published. Thanks for submitting this issue!
