### ISSUE TITLE
Support prebuilt ELF projects

### ISSUE THREAD

**Issue by krister-ts** [callwyat/mplab-extension#12]
I use cmake to generate elf output and debug in MPLAB X. How can I use a project made from imported ELF with this extension?

**Comment by callwyat** [comment]
Now that is a use case I haven’t thought of yet. It should be fairly easy to add that functionality, and it might even fix Issue #4 I’ll see what I can do, but I have limited time to work on this project, so if you want to put something together and make a pull request you can get something very quickly.

**Comment by krister-ts** [comment]
> if you want to put something together and make a pull request you can get something very quickly.

Not sure where to start. Never worked on vscode extensions before.

**Comment by callwyat** [comment]
Thanks for the great suggestion! I added a second debug type called "mdb" (Microchip Debug Adapter) to the project that will allow you to use ELF files directly. You can test it out in Version 0.1.13 (which is a prerelease). Let me know if you have any problems with it!

**Comment by callwyat** [comment]
> > if you want to put something together and make a pull request you can get something very quickly.
> 
> Not sure where to start. Never worked on vscode extensions before.

I hadn't either when I started this project, thankfully the documentation for how to get started was very helpful. I still am not very good at TypeScript though, but I do what I can.

**Comment by krister-ts** [comment]
> Thanks for the great suggestion! I added a second debug type called "mdb" (Microchip Debug Adapter) to the project that will allow you to use ELF files directly. You can test it out in Version 0.1.13 (which is a prerelease). Let me know if you have any problems with it!

Thanks so much! I will try this out tomorrow morning.

**Comment by pustekuchen91** [comment]
Hey Guys,

i cant test debugging at this moment (because i need to upgrade to win11 because i'm developing via WSL in a devcontainer, and need to passthrough the icd3), but i have an improvment proposal

if "device" is set in the configuration, but "toolType" isnt. 
The error message is: "Failed to connect to target device null".

this can be a bit missleading. Maybe this is an issue because the hwtool isnt available yet in my environment.
