### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by pustekuchen91** [callwyat/mplab-extension#15]
Hello, 

i'm developing in a devcontainer with the following image `mcr.microsoft.com/devcontainers/cpp:0-ubuntu-22.04`.

When trying to execute the build task, it wont find `make`
 Executing task: /opt/microchip/mplabx/v6.15/mplab_platform/bin/make CONF="default" 

is linux already supported or just windows?

**Comment by pustekuchen91** [comment]
EDIT: mdb.sh is also missing... something is strange with the actual setup

[Building a Project Outside of MPLAB X IDE](https://microchipdeveloper.com/mplabx:work-outside-build-project)

The path for linux seem not to be valid for the latest mplabx version.

`make` seems not to be installed by the installer.
```
vscode ➜ .../mplabx/v6.15/mplab_platform/bin $ ll
total 8
drwxr-xr-x  2 root root 4096 Oct 12 14:56 ./
drwxr-xr-x 21 root root 4096 Oct 12 14:56 ../
-rwxr-xr-x  1 root root    0 Aug  9 15:18 mplab_ide*
-rwxr-xr-x  1 root root    0 Aug  9 15:18 mplab_ipe*
```

but `make` is generally available, which could also be used? 

```
scode ➜ .../mplabx/v6.15/mplab_platform/bin $ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

maybe an option in the extension would be nice

**Comment by pustekuchen91** [comment]
Sorry, the mplabx installer seems to not install correctly, if java jre isnt installed.

**Comment by callwyat** [comment]
I’m glad you were able to get it all figured out! To make sure I understand the solution, MPLABX was not installing correctly because Java JRE needed to be installed first?

**Comment by pustekuchen91** [comment]
yes, it seems to be so.
