### ISSUE TITLE
Support for raw mdb debug session

### ISSUE THREAD

**Issue by pustekuchen91** [callwyat/mplab-extension#16]
I'm developing in an environment without MPLABX IDE and nbprojects, we use qbs as a build tool. 

the "program" property in the launch.json expects a path to an MPLAB X Project.

If i see correctly there is a type `mdb` which isnt implemented yet. 

It would be nice, if this extension would allow me to debug with mdb by using a elf file.

**Comment by pustekuchen91** [comment]
duplicate of #12 

didnt see the issue and v0.1.12 was installed.

**Comment by callwyat** [comment]
@pustekuchen91  So 0.1.13 works for you?

**Comment by pustekuchen91** [comment]
I was not able to test it because I was not able to redirect the icd3 from Windows to the devcontainer via WSL. Next week I will try it on a native Linux system. If it works, I will give feedback.

@callwyat  thanks for you work on this extension
