### ISSUE TITLE
MPLAB Snap support

### ISSUE THREAD

**Issue by SlyCedix** [callwyat/mplab-extension#17]
```<platformTool>snap</platformTool>```

The snap seems to already be functional, I am able to use it to debug without issue.

Just making this issue so that it can be added to the README

**Comment by callwyat** [comment]
Thanks for creating this issue! It looks like this is the rare case where Microchip actually used the same name in MPLAB X as they did in MDB, so the fall back behavior of using the MPLAB X name  worked 😅 I’ll go ahead and add it to the validated list. 😊

**Comment by callwyat** [comment]
Official support for the snap tool has been added in v0.1.18

**Comment by SlyCedix** [comment]
I also have access to an ICD3, ICD4, ICD5, Real ICE, and PicKit5 if it'd be helpful to test those. Just let me know what you'd like verified and I can do those after the new year.

I actually only use the snap because it seems to be the one with the least intermittent connection issues (Transmission on Endpoint 2, specifically)

**Comment by callwyat** [comment]
Oh awesome! If haven't been able to verify the ICD5 and Real ICE, so if you could check those too out I would much appreciate it!

I haven't heard of the snap until now. It doesn't surprise me that it is more reliable see at it only does one thing 😄
