### ISSUE TITLE
Creating mdb scripts

### ISSUE THREAD

**Issue by JoeLowtech** [callwyat/mplab-extension#20]
Hello,

I want to debug microchip mcus without mplab and straight from cli. For this I want to use mdb scripts. As I understand your extension, it is using mdb scripts for debugging?

The problem is that the offical document does not explain in detail, on how to set up a script for a certain hardware and debugger. I understand, that I somehow have to add the configuration of my debugger. But there are no examples from microchip. So before I go into a trial and error session, I figured I asked you. Maybe you have some insights and could send me in the right direction on where to look? :)

**Comment by callwyat** [comment]
Hi!

You are correct. This extension uses the Microchip Debugger to communicate with development tools. This extension essentially puts a [Debug Adapter](https://microsoft.github.io/debug-adapter-protocol/) around the MDB, which allows it to work with VSCode, and theoretically any editor that supports the Debug Adapter Protocol. (in practice a little bit of work needs to be done on each editor to launch the adapter, and I'm not sure how to package it for any editor outside of VSCode.)

As for how I figured out how to use it, I primarily used the [MDB Documentation](https://www.microchip.com/content/dam/mchp/documents/DEV/ProductDocuments/UserGuides/50002102G.pdf) that Microchip provides, the MDB `help` command, and trial and error.

Something that I wish I had found sooner was the `HWTOOL SUPPORTED` command. This command will list all the debugger tools that the running versions of MDB supports.

From what I understand of MDB scripts, they are just a file of newline separated MDB commands where the output is printed to the console, or redirected to a file. It also looks like you'll need to use commands like `WAIT`, which I haven't needed to use.

If you want an example of how it works, you can always run this extension and look at the Debug Output in VSCode. It will show you everything that gets written and read.

**Comment by callwyat** [comment]
Feel free to reopen the issue if you have more questions. 😊

**Comment by JoeLowtech** [comment]
Thank you callywat for your reply. With your information I was able to start the ICD5 debugger and flash the mcu. To my suprise it was pretty simple: 
```
device PIC24FJ64GA002
pwd  
hwtool icd5  
program ../dist/Tests_on_Hw/debug/myimage.debug.elf  
run
```  
But it does connect twice to the debugger... once when calling `hwtool` and once when `programming`. 
MPlab does connect only once. I wonder how they are doing this...

Anyway it does work for now :). Thanks 
Trying your extension with vs is on my to do list as well.

**Comment by callwyat** [comment]
I’m glad I could help!

Could you send me an example of what you mean by “tries to connect twice”? MPLAB only shows what MDB responds with, where the extension shows everything it writes to the MDB and all of the MDBs responses. Which could look like the extension trying to connect twice.

**Comment by JoeLowtech** [comment]
Hello callwyat,
I think there is a misunderstanding. The difference is between my script and the mplabx ide. Not between your extension and mplabx.

My little script connects to the debugger twice. Once when executing command `hwtool icd 5` and once when executing `program`. MPLAB X on the other hand, is somehow connecting once and also programming. You can also hear the difference. With my script the debugger is "clicking " twice. With MPLAB X only once.

**A little background why this concerns me :) :**
Connecting takes a couple of seconds each time you connect to the debugger. My intent is to use the script for automated testing and developing. My guess is each test-scenario will take up 15- 30 seconds with my current approach. (Starting mdb, connecting, programming, running,disconnecting). This is too much time if I want to run a lot of test-scenarios.

I have not found a way with the mdb CLI to connect and program in one step so far. Also I had no time to look at your extension for comparison. Hopefully I can do that soon : ) .
**Command Line output:**
```
hwtool icd5
Jan 24, 2024 4:19:22 PM com.microchip.mplab.nativeloader.NativeLoader loadNativeLibrary
INFORMATION: Library resource path: libs\USBAccessLink_3_46.dll
Jan 24, 2024 4:19:22 PM org.openide.util.NbPreferences getPreferencesProvider
WARNUNG: NetBeans implementation of Preferences not found
Jan 24, 2024 4:19:29 PM com.microchip.mplab.mdbcore.RealICETool.RIMessages OutputMessage
INFORMATION:




 

*****************************************************



Connecting to MPLAB ICD 5 - USB mode...

Currently loaded versions:
Application version...........02.00.64
Boot version..................00.00.04
FPGA version..................01.00.01
PCB version...................2
Script version................00.05.85
Script build number...........d33d758f73
Tool pack version ............2.1.222
Target voltage detected
Target device PIC24FJ64GA002 found.
Device Revision Id  = 0x3046
Device Id = 0x4470000

program ../dist/Tests_on_Hw/debug/FHAD46E.debug.elf
Programming target...
Jan 24, 2024 4:19:47 PM com.microchip.mplab.mdbcore.RealICETool.RIMessages OutputMessage
INFORMATION:



 

*****************************************************



Connecting to MPLAB ICD 5 - USB mode...

Currently loaded versions:
Application version...........02.00.64
Boot version..................00.00.04
FPGA version..................01.00.01
PCB version...................2
Script version................00.05.85
Script build number...........d33d758f73
Tool pack version ............2.1.222
Target voltage detected
Target device PIC24FJ64GA002 found.
Device Revision Id  = 0x3046
Device Id = 0x4470000

Calculating memory ranges for operation...

Erasing...


The following memory area(s) will be programmed:
program memory: start address = 0x0, end address = 0x83ff
configuration memory


Programming/Verify complete
Program succeeded.
run
```

**MPLABX Debugger Output:**
*****************************************************

 ```
Connecting to MPLAB ICD 5 - USB mode...

Currently loaded versions:
Application version...........02.00.64
Boot version..................00.00.04
FPGA version..................01.00.01
PCB version...................2
Script version................00.05.85
Script build number...........d33d758f73
Tool pack version ............2.1.222
Target voltage detected
Target device PIC24FJ64GA002 found.
Device Revision Id  = 0x3046
Device Id = 0x4470000

Calculating memory ranges for operation...

Erasing...


The following memory area(s) will be programmed:
program memory: start address = 0x0, end address = 0x83ff
configuration memory


Programming/Verify complete

Running
Target Halted
```
