### ISSUE TITLE
Please support PKOBSKDEPlatformTool

### ISSUE THREAD

**Issue by AlonRR** [callwyat/mplab-extension#21]
"\<platformTool\>PKOBSKDEPlatformTool\</platformTool\>"
I've been trying unsuccessfully to use the debug.

**Comment by callwyat** [comment]
Thanks for submitting this issue! Sorry I have been slow to address it. What version of MPLAB are you using? This seams to be an older tool.

**Comment by callwyat** [comment]
Hello again! I went ahead and created Pre-Release version 0.1.25. This version attempts to add support for the "PKOBSKDEPlatformTool" tool, but I may have created the MDB Key wrong. Please give it a test and let me know if it works!

**Comment by callwyat** [comment]
Published version 0.1.26. Please reopen this issue if your problem persists.
