### ISSUE TITLE
Not able to debug.

### ISSUE THREAD

**Issue by timscheuermann** [callwyat/mplab-extension#22]
I try to debug my mplab project.
Building works, but debugging does not.
When hitting F5 + clicking MPLABX Debug, it says "Cannot read properties of undefined (reading 'replace')"
![Screenshot 2024-03-06 172033](https://github.com/callwyat/mplab-extension/assets/50117699/b4e42bd8-8b43-47a4-88fe-5242dcf995f4)
![Screenshot 2024-03-06 172132](https://github.com/callwyat/mplab-extension/assets/50117699/69de4887-2bef-4012-bd5e-e0373a56bd57)

I am in my Firmware folder, which contains the Project.X Folder.

Thanks.

**Comment by callwyat** [comment]
Thanks for submitting this issue! Do could you send me the contents of your `launch.json`? Or was this done before setting one up?

**Comment by timscheuermann** [comment]
I did not add a launch.json. I added one like described in the readme and it works.
Thank you

**Comment by callwyat** [comment]
I'm glad you were able to get moving along again :) I was able to replicate the bug by not having a `launch.json` myself, and have published a fix in version 0.1.28.
