### ISSUE TITLE
nbproject/Makefile-default.mk: No such file or directory

### ISSUE THREAD

**Issue by harrkout** [callwyat/mplab-extension#24]
Hello, the extension used to work great, but now I get the following error 

```
C:/Program Files/Microchip/MPLABX/v6.15/gnuBins/gnuWin32/bin/make -f nbproject/Makefile-"default".mk SUBPROJECTS= .build-conf
make[1]: Entering directory '${ProjectPath}/firmware/GCubeSatMeas_Testing_v0.2.1.X'
make[1]: nbproject/Makefile-default.mk: No such file or directory
make[1]: *** No rule to make target 'nbproject/Makefile-default.mk'.  Stop.
make[1]: Leaving directory '${ProjectPath}\firmware/GCubeSatMeas_Testing_v0.2.1.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make: *** [.build-impl] Error 2
```

I tried regenerating the makefile with the following command, but to no avail:
 `C:\Program Files (x86)\Microchip\MPLABX\v5.35\mplab_platform\bin\prjMakefilesGenerator.bat .`

Any ideas?

**Comment by callwyat** [comment]
0.1.28 was released yesterday, it shouldn’t have changed anything in the build task. Some things you can try are:

1. Run the build in MPLABX and make sure that still works.

If the build works in MPLABX, the problem is in the extension, and you can do the following until I have a fix.

2. Revert to an older version of the extension by changing the version in the extension view.

Please let me know the results!

**Comment by callwyat** [comment]
P.S. You can run that script automatically from within VSCode by running the: `MPLABX: Update private make files` command from the command pallet.

**Comment by harrkout** [comment]
I tried downgrading the version and regenerating the files with the 
``` & 'C:\Program Files\Microchip\MPLABX\v6.15\mplab_platform\bin\prjMakefilesGenerator.bat . ``` command, but nothing changed.

I'm not sure if the problem lies with the MPLABX or the extention, as the file it seeks is from here `Makefile-impl.mk` :

```
# build
.build-impl: .build-pre
	${MAKE} -f nbproject/Makefile-${CONF}.mk SUBPROJECTS=${SUBPROJECTS} .build-conf
```

and for some reason maybe the extension does not recognize the `CONF` macro.

I'll keep looking

**Comment by harrkout** [comment]
I also get the following, so the problem may be with my MPLAB:

```
Executing task: C:\Program Files\Microchip\MPLABX\v6.15\gnuBins\gnuWin32\bin\make.exe CONF="default" 

rm -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl refman.pdf
rm: cannot remove `*.ps': Invalid argument
rm: cannot remove `*.dvi': Invalid argument
rm: cannot remove `*.aux': Invalid argument
rm: cannot remove `*.toc': Invalid argument
rm: cannot remove `*.idx': Invalid argument
rm: cannot remove `*.ind': Invalid argument
rm: cannot remove `*.ilg': Invalid argument
rm: cannot remove `*.log': Invalid argument
rm: cannot remove `*.out': Invalid argument
rm: cannot remove `*.brf': Invalid argument
rm: cannot remove `*.blg': Invalid argument
rm: cannot remove `*.bbl': Invalid argument
Makefile:27: recipe for target 'clean' failed
make: *** [clean] Error 1
```

**Comment by callwyat** [comment]
Were you able to find the source of the problem?

**Comment by harrkout** [comment]
No, I never solved it unfortunately. I think it has to do with something I changed rather than your project, because I was using it just fine for some time
