### ISSUE TITLE
Failure to find a "default" configuration in [object Object]

### ISSUE THREAD

**Issue by jetacpp** [callwyat/mplab-extension#25]
Hello,

I have MPLABX project configured and worked fine in IDE. When setting up the same project in VSLAB Extension (0.1.28), it can compile and build find. However, when clicking MPLABX Debug button the following message was produced "Failure to find a "default" configuration in [object Object]"

**Comment by callwyat** [comment]
Can you attach the configuration file for the project? (nbproject/configuration.xml)

**Comment by jetacpp** [comment]
Sure, here is the `configuration.xml` file
[configurations.zip](https://github.com/callwyat/mplab-extension/files/15184196/configurations.zip)

**Comment by callwyat** [comment]
I was able to find the problem! There are two ways you can address it
1. Create a launch.json and add `"configuration" = "Release"` to it's properties
2. I have released pre-release 0.1.29, which should pick the correct configuration for you since your project only has one configuration.

I need to make up a unit test for this before I make a release version (0.1.30). That should be available in the next few days.

**Comment by jetacpp** [comment]
Version 0.1.29 seemed to get passed this error. However another error popped up "Failure to find the output folder: demo.X/dist/Release/debug".  I have the build files in "demo.X/dist/Release/production" instead. I am not sure I found this setting in the `configurations.xml` file

**Comment by callwyat** [comment]
hmm that is odd. In my testing it should have defaulted to `production` instead of `debug`. Did you end up making a Build Task or Launch Configuration? If so, could you send me your `task.json` and `launch.json` files from the `.vscode` folder?

**Comment by jetacpp** [comment]
I only created `launch.json` and here is its content:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "mplabx",
            "request": "launch",
            "name": "MPLABX Debug",
            "program": "${workspaceFolder}/",
            "stopOnEntry": true,
            "preLaunchTask": "MPLABX Build",
            "configuration": "Release",
            "debug": true,
        }
    ]
}`

If I change the above `debug: true` to `false` then the error is fixed. But then it wasn't able to program the device "Failed to connect to target device null` 
`HwTool EdbgTool

>null`

This is incorrect. I did not connect or power on the Edbg debugger. I used an external JTAG debugger. The Mplab IDE was able to connect and debug fine.

**Comment by callwyat** [comment]
I don't know why it took me so long to realize the issue here was I hadn't registered the "EDBG" tool with the extension. You should be able to debug now in version v0.2.2
