### ISSUE TITLE
Working extension without full MPLABX IDE preinstalled

### ISSUE THREAD

**Issue by mrtuborg** [callwyat/mplab-extension#26]
Hello,

I have recently developed some small script (picKit.sh) that makes deal with MPLAB debugger without installation the whole IDE on the computer. So it uploads elf-file that used as an argument to the pic controller and runs mdb session to be able to debug uploaded application with console commands. MDB is part of prepared docker-container, I have also separate container for building software without installing MPLABX as well. So, my setup working well under CI/CD in Gitlab with this, but I believe it still not comfortable to work with for the developers.

Your extension is attracted my attention and I want to propose collaboration on this. Of course, I could do fork of your work and incorporate all I need myself in my time. I do not know if you will found my way attractive to have as a part of your work or not. But what I need - is some guidance. I am familiar a bit how your extension works, I have debugged it to understand better. But typescript/javascript is not my area of deep knowledge, so I need some kind of guidance. Like maybe, logging to understand how it is executing my script inside, that I am trying to insert into the mplabPath class.

Is there any way we could contact and discuss this?

It will help me a much if I can ask just couple questions in Slack/Discord or whatever are you using...

**Comment by callwyat** [comment]
Hello @mrtuborg,

I do like the idea of not requiring the full installation of MPLAX along side this extension a would like to integrate this feature. 

As for the how, I would like to review the work you have done then we can discuss further. Is there a repo somewhere where I can find your work?

Thanks!

**Comment by mrtuborg** [comment]
It is on private gitlab repo for now. We can have a call and I can demonstrere how it works. 
I believe my script needs to be rewritten to python (that I can easy to do) to work seamlessly on Windows as well.

Write me mail to Vladimir.Nosenko at google mail server.

**Comment by callwyat** [comment]
Version 0.1.32 contains settings to override all the tool paths that are used by the extension. You should be able to override the microchip debugger path to point your custom location.
