### ISSUE TITLE
Debugging Using PICKit4 ，failed to connect target device

### ISSUE THREAD

**Issue by zhang00956** [callwyat/mplab-extension#6]
hello,I use VSLABX 0.1.6 version.and comply recommend task.json and launch.json,but I can`t enter debug mode.
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "mplabx",
            "request": "launch",
            "name": "MPLABX Debug",
            "program": "${workspaceFolder}/pic32mz_lunch.X/",
            "stopOnEntry": true,
            "preLaunchTask": "MPLABX Build",
            "configuration": "default",
            "debug": true
        }
    ]
}
>Device PIC32MZ2048EFH144
set communication.activationmode nohv
>set communication.interface swd
>set communication.interface.jtag 2wire
>set communication.speed 2.000
>set debugoptions.debug-startup Halt at main
>set debugoptions.reset-behaviour Main
Error: invalid parameter.
>set debugoptions.simultaneous.debug false
>set debugoptions.useswbreakpoints false
>set freeze.timers false
>set memories.aux false
>set memories.bootflash true
>set memories.configurationmemory true
>set memories.configurationmemory2 true
>set memories.dataflash true
>set memories.eeprom true
>set memories.exclude.configurationmemory true
>set memories.flashdata true
>set memories.id true
>set memories.programmemory true
>set memories.programmemory.ranges 1d000000-1d1fffff
>set poweroptions.powerenable false
>set programoptions.donoteraseauxmem false
>set programoptions.eraseb4program true
>set programoptions.ledbrightness 5
>set programoptions.pgcconfig pull down
>set programoptions.pgcresistor.value 4.7
Error: invalid parameter.
>set programoptions.pgdconfig pull down
>set programoptions.pgdresistor.value 4.7
Error: invalid parameter.
>set programoptions.pgmentry.voltage low
>set programoptions.pgmspeed Med
>set programoptions.preservedataflash false
>set programoptions.preserveeeprom false
>set programoptions.preserveprogramrange false
>set programoptions.preserveuserid false
>set programoptions.program.otpconfig false
>set programoptions.programcalmem false
>set programoptions.programuserotp false
>set programoptions.testmodeentrymethod VDDFirst
>set ptgProgramImage false
>set ptgSendImage false
>set toolpack.updateoptions toolpack.updateoptions.specifictoolpack
>set toolpack.updateoptions.packversion 1.14.1651
>set voltagevalue 3.25
>set 冻结所有其他外设 true
>set 安全段。分部编程 FullChipProgramming
>HwTool PICKit4
>

and then it show an window:  "failed to connect target device"。I am sure that MPLABX program to go closed, and MPLABX could connect KIt4,and MPLABX.exe  has closed 。I try my best ，but can`t solve the problem
[configurations - 副本.xml.txt](https://github.com/callwyat/mplab-extension/files/11084980/configurations.-.xml.txt)

**Comment by callwyat** [comment]
There has been a bug for a while now with the PICKIT4 unfortunately. Something about the configuration as listed in the project file makes the connection fail. Unfortunately, I haven’t had much time to dig into this issue.

**Comment by callwyat** [comment]
I have released a preview version of the extraction that should fix this issue. Will you please update to 0.1.7 and let me know if your 4 Series programmers work?

**Comment by callwyat** [comment]
You’ll need to open up the extension and select “Switch to Pre-Release“

**Comment by zhang00956** [comment]
I have tested ,it can enter debug mode,but it can't work well ，often stuck。in chinese :能用，但又不能用.
I am sorry ,I can`t describe the extraction status in english。😂

**Comment by callwyat** [comment]
Is it getting stuck as soon as you enter debug mode, or does it run for a bit before getting stuck? If you are getting stuck right after programming completes, the problem may be that “halt on entry” is true and you need to hit the run button.

If you could send me the debug output, I might be able to figure it out.

**Comment by zhang00956** [comment]
> Is it getting stuck as soon as you enter debug mode, or does it run for a bit before getting stuck? If you are getting stuck right after programming completes, the problem may be that “halt on entry” is true and you need to hit the run button.
> 
> If you could send me the debug output, I might be able to figure it out.

when I add breakpoint,The program will stuck ,and take a long time to pause。
if I click pause,The program will stuck,and take a long time to pause too，then out put this logs :
[debuglog.txt](https://github.com/callwyat/mplab-extension/files/11106932/debuglog.txt)

**Comment by zhang00956** [comment]
I find ,if I use jlink in MPLABX debug,jlink will work better than kit4。Does the extraction support jlink debug?

**Comment by callwyat** [comment]
Looking at the log, I can see why there is such a huge delay when a breakpoint is hit. Currently the extension is using “backtrace full” which dumps the stack, and all the local variables. It looks like you have some HUGE local variables, so the backtrace is taking a long time to read. I’ll need to put some thought into how to address large dumps like this. Feel free to pitch in any thoughts you may have, or try cloning the repo and poking around a bit.My first thought is to use just “backtrace” which should retain much less data, helping to keep things snappy.Wyatt J Callister Sent from my iPhoneOn Mar 29, 2023, at 18:37, little niu ma ***@***.***> wrote:﻿

Is it getting stuck as soon as you enter debug mode, or does it run for a bit before getting stuck? If you are getting stuck right after programming completes, the problem may be that “halt on entry” is true and you need to hit the run button.
If you could send me the debug output, I might be able to figure it out.

when I add breakpoint,The program will take a long time to pause。
if I click pause,The program will take a long time to pause，then out put this logs :
debuglog.txt

**Comment by zhang00956** [comment]
I used FreeRTOS and TCP/IP in the program

**Comment by callwyat** [comment]
It doesn’t currently, but tools are typically not to hard to add. I just need to know what the tool name is in the project file, and the name of the tool in the MDB program. I’ll put a doc together of how to find those items.Wyatt J Callister Sent from my iPhoneOn Mar 29, 2023, at 18:47, little niu ma ***@***.***> wrote:﻿
I find ,if I use jlink in MPLABX debug,jlink will work better than kit4。Does the extraction support jlink debug?

**Comment by callwyat** [comment]
A TCP/IP stack could definitely do that.Wyatt J Callister Sent from my iPhoneOn Mar 29, 2023, at 19:45, little niu ma ***@***.***> wrote:﻿
I used FreeRTOS and TCP/IP in the program

**Comment by callwyat** [comment]
Sorry for the delay. In order to add the JLINK tool to the the supported list, I just need the name of the tool from the project file. A little more documentation on this process can be found here: https://github.com/callwyat/mplab-extension/blob/main/readme.md#debugger-notes

**Comment by zhang00956** [comment]
> Sorry for the delay. In order to add the JLINK tool to the the supported list, I just need the name of the tool from the project file. A little more documentation on this process can be found here: https://github.com/callwyat/mplab-extension/blob/main/readme.md#debugger-notes

      <toolsSet>
        <developmentServer>localhost</developmentServer>
        <targetDevice>PIC32MZ2048EFH144</targetDevice>
        <targetHeader></targetHeader>
        <targetPluginBoard></targetPluginBoard>
        <platformTool>jlink</platformTool>
        <languageToolchain>XC32</languageToolchain>
        <languageToolchainVersion>4.21</languageToolchainVersion>
        <platform>3</platform>
      </toolsSet>

**Comment by callwyat** [comment]
v0.1.8 should support the J-Link tool :)

**Comment by callwyat** [comment]
Closed do to inactivity
