### ISSUE TITLE
"No voltage detected on VDD"

### ISSUE THREAD

**Issue by NatiUnger** [callwyat/mplab-extension#8]
Hi,
Using VSLABX 0.1.10,
Just imported my MPLAB project to the "sampleWorkspace" from this repository and "Open folder" with VScode.
When try to debug i'm getting this error:
![image](https://github.com/callwyat/mplab-extension/assets/89031734/3545c86d-04a9-4c1c-b99e-fd92effee8c0)

I just want to add that the power is on and i can program the device using the sample project on mplab.

Thanks a lot for this extension, I'm getting such bad performance from mplab that i'm almost ditching it (used to work with st cube iar and segger)

**Comment by callwyat** [comment]
Hello,

Thanks for the kind words! That sounds like the same reason I started making this extension. 😊

As for your problem. This error is normally generated when the VDD of the PICKIT is not connected to the VDD of the target circuit. Is your intent that the target circuit should be supplying power? Or are you trying to power the target circuit from the PICKIT?

If you are trying to power the target circuit from the PICKIT, you will need to enable sending parts of the programmer configuration to the PICKIT. All of the configuration used to be sent, but it was causing reliability issues with the 4 series of tools, so it was disabled and now needs to be explicitly turned on for each line of the configuration you want to use in the launch.json file.

**Comment by NatiUnger** [comment]
Hi,
Well yes i'm using picKit4 :( and the board is self powered,
I didnt understood how to change launch.json file.
So I just solder the VDD pin of the picKit to the board supply power.

Now I got this error:
[debugtool.txt](https://github.com/callwyat/mplab-extension/files/12209889/debugtool.txt)

![image](https://github.com/callwyat/mplab-extension/assets/89031734/43b4c792-6257-4565-aaac-2d4813220a37)


Please advice :)

**Comment by callwyat** [comment]
Normally, the header that the pickit plugs into on your board will have VDD exposed for this purpose. Unfortunately, without at least a simplified schematic I don’t think I’ll be able to figure this one out, but it does seam like a hardware problem to me. Was the project working when you were using your other setup? Did you have PICKIT power turned on?

**Comment by NatiUnger** [comment]
H,
Well yes. Project is compiled and debugged on MPLAB 😊
PicKit is powered up…

**Comment by callwyat** [comment]
Closed do to inactivity
