### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by AndreaTurro** [callwyat/mplab-extension#9]
Hi, thanks for your work, I have a problem building my project, I get this error:
` *  Executing task: ""c:\Program Files\Microchip\MPLABX\v5.45\gnuBins\gnuWin32\bin\make.exe" CONF="default"" 

c:/Program Files/Microchip/MPLABX/v5.45/gnuBins/gnuWin32/bin/make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'C:/PROJ/XT4/firmware/XT4.X'
cd ../../library/GPS_DRV.X && c:/Program Files/Microchip/MPLABX/v5.45/gnuBins/gnuWin32/bin/make  -f Makefile CONF=default
'c:/Program' is not recognized as an internal or external command,
operable program or batch file.
nbproject/Makefile-default.mk:1366: recipe for target '.build-subprojects' failed
make[1]: *** [.build-subprojects] Error 1
make[1]: Leaving directory 'C:/PROJ/XT4/firmware/XT4.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make: *** [.build-impl] Error 2

 *  The terminal process "cmd /d /c ""c:\Program Files\Microchip\MPLABX\v5.45\gnuBins\gnuWin32\bin\make.exe" CONF="default""" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. `
It seems to me it is related to windows path handling for commands, do you have any suggestions?

**Comment by callwyat** [comment]
Thank you for submitting this issue! It looks like the space in “Program Files” is causing the issue, which I thought I fixed before I even erased the extension. I’ll be able to take a look at this this weekend. In the mean time, can you post the version of the extension you are using?

**Comment by AndreaTurro** [comment]
Sure! I am using v0.1.10!

**Comment by callwyat** [comment]
I am not able to recreate the failure in my test environment. Could you send me a copy of your `task.json` file? Thanks!

**Comment by AndreaTurro** [comment]
Hi, sorry for the delay, only saw your message yesterday! 
Here is the code:
[tasks.txt](https://github.com/callwyat/mplab-extension/files/12515094/tasks.txt)
And thanks again for your work!

**Comment by callwyat** [comment]
I looked at the console output that you originally posted a bit closer and this line stood out to me `cd ../../library/GPS_DRV.X && c:/Program Files/Microchip/MPLABX/v5.45/gnuBins/gnuWin32/bin/make`. This line happens after `make[1]` which indicates to me it is being called by the `make` process. Is this project trying to build a different project?

**Comment by AndreaTurro** [comment]
Yes, it has 3 different project inside, could that be a problem?

**Comment by callwyat** [comment]
I think so, it looks like the make is getting called successfully by VSLab, the the “cd ../../library/GPS_DRV.X” should work, but because of the space between “Program” and “Files” the command line gets confused and thing everything after “Program” is arguments. I’m guessing the build works fine when using MPLAB though?

**Comment by AndreaTurro** [comment]
Yes with MPLAB I have no problem building/programming/debugging, would you like a log?

**Comment by callwyat** [comment]
That would be great!

**Comment by AndreaTurro** [comment]
Here it is! [clean build log.txt](https://github.com/callwyat/mplab-extension/files/12669775/clean.build.log.txt)

**Comment by callwyat** [comment]
I have created a prerelease that should hopefully address this issue. Can you install 0.1.11 and verify if building works for you now?

**Comment by callwyat** [comment]
@AndreaTurro Does 0.1.11 work for you?

**Comment by callwyat** [comment]
If the issues still persists, please reopen this issue.

**Comment by AndreaTurro** [comment]
Hello, sorry for the delayed response. I tried the version you release but it seems it still doesn't work. I made some tests and could not figure it out, I'll  leave the logs here.
[Debug .txt](https://github.com/callwyat/mplab-extension/files/12879858/Debug.txt)

**Comment by callwyat** [comment]
I did some testing with prebuilt tasks and did find issues using MPLABX v6.15, so I went back to v6.05 and the problem went away. That being said it looks like you are using 5.45. :/

**Comment by AndreaTurro** [comment]
I should try to migrate the project to newer versions of MPLAB X then. I already tried once and it didn't go that well but i'll try again. Thanks for the help!

**Comment by callwyat** [comment]
I would also recommend trying to get the build to work outside of MPLAB. Here is an example how how I did it before I made the VSLAB extension 

https://github.com/callwyat/Quiet-Firmware/blob/b93e00f856133eb05ce62f2af0230c59c75eb23d/.vscode/tasks.json 

it was a lot harder to get setup, and didn’t have a problem matcher, but if you do get the build to work, you can reuse the VSLAB problem matcher, and use the “Microchip Debug Adapter” configuration to debug using the ELF file. 

If you do end up getting the build to work outside of MPLAB to work, please send me a snip so I can fix the extension for you!
